#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

node_string=$(grep "node" .workspace_config | awk '{print $ 2}')
container=techart_nodejs_$node_string

docker start $container
docker exec -tw $(pwd) -u user $container bash -c "cd $(pwd); pwd; npx lint-staged"
